services:
  offa:
    image: oidfed/offa:main
    restart: unless-stopped
    volumes:
      - ./offa/config.yaml:/config.yaml:ro
      - ./offa:/data
    networks:
      - caddy

  # This would be your service
  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - caddy

networks:
  caddy:
    external: true
    name: caddy-network
