server:

logging:
  access:
    level: debug
    stderr: true
  internal:
    level: debug
    stderr: true

sessions:
  ttl: 3600
  cookie_domain: oidf-pilot.edugain.org

auth:
  - domain: op2.oidf-pilot.edugain.org
#  - domain: whoami-oidf-pilot.aai.garr.it
#    require:
#      groups: user

signing:
  key_storage: /data
  alg: ES512

federation:
  entity_id: https://rp1.oidf-pilot.edugain.org
  trust_anchors:
    - entity_id: https://ta.oidf-pilot.edugain.org
      #    - entity_id: https://ia1.oidf-pilot.edugain.org
  authority_hints:
    - https://ia1.oidf-pilot.edugain.org
  display_name: "eduGAIN OIDF Pilot RP1"
  organization_name: "eduGAIN"
  organization_uri: "https://edugain.org"
  contacts:
    - support@edugain.org
  use_resolve_endpoint: true
  use_entity_collection_endpoint: true

debug_auth: true

