server:
  port: 8765
signing:
  alg: ES256
  key_dir: "/data/signing"
federation_data:
  entity_id: "https://ta.oidf-pilot.edugain.org"
  federation_entity_metadata:
    display_name: "eduGAIN OIDF Pilot Trust Anchor"
    organization_name: "eduGAIN"
    organization_uri: "https://edugain.org"
    contacts:
      - support@edugain.org
  metadata_policy_file: "/data/metadata-policy.json"
storage:
  backend: json
  data_dir: "/data/storage"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  enroll:
    path: "/enroll"
